#!/bin/sh
#
# /usr/lib/setup/CreatePartitions
#
# Slackware 10.2 Kickstart installation.
#
# comments to: vonatar@slack-kickstart.org
# http://www.slack-kickstart.org
#
# Last Revision: 19/09/2006 by vonatar
#
# includes common functions
. /usr/lib/setup/include/functions.inc

#########################
#    HDD partitioning   #
#########################
#
# Creates device nodes
# Note: makedev command seems to be gone
if ! ps aux | grep -e 'udevd' | grep -q -v -e 'grep' ; then
	/usr/sbin/makedevs.sh >> "${FH_LOG}" 2>&1
fi
for DRIVE in $(awk -F':' '{ print $1 }' "${TMP}/Partitions" | sort | uniq); do
	# Clear MBR & Partition table
	dd if=/dev/zero of=${DRIVE} bs=512 count=1 >> "${FH_LOG}" 2>&1
	# Create partitions
	printf "Creating partitions on %s..... " "${DRIVE}" | \
		tee -a "${FH_LOG}"
	grep -e "^${DRIVE}" "${TMP}/Partitions" | \
		awk -F':' '{ print $5 }' | \
		sfdisk --no-reread --force ${DRIVE} -uM >> "${FH_LOG}" 2>&1
	# Test Partitions
	if ! sfdisk -V ${DRIVE} >> "${FH_LOG}" 2>&1 ; then
		printf "[FAIL]\n" | tee -a "${FH_LOG}"
		printf "\nFATAL ERROR on partitions table - Aborting\n" | \
			tee -a "${FH_LOG}"
		printf "HINT: Check tty4 for errors.\n" | tee -a "${FH_LOG}"
		printf "HINT: Partitions exceeding %s size ?\n" "${DRIVE}" |\
			tee -a "${FH_LOG}"
		FireBugInfo
		exit 1
	fi # if ! sfdisk -V ...
	printf "[OK]\n" | tee -a "${FH_LOG}"
done # for DRIVE
#
# Device creation: now we need to create dev nodes for the new partitions
# Note: makedev command seems to be gone.
if ! ps aux | grep -e 'udevd' | grep -q -v -e 'grep'; then
	/usr/sbin/makedevs.sh >> "${FH_LOG}" 2>&1
fi
# EOF
